# Generated by Django 5.0 on 2023-12-30 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('clicks', models.IntegerField()),
                ('views', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('click', models.IntegerField()),
                ('views', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('imgUrl', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_mangement.advertiser')),
            ],
        ),
    ]
