# Generated by Django 5.0 on 2024-01-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0002_remove_ad_click_remove_ad_views_ad_approve_click_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='clicker_ip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='view',
            name='viewer_ip',
            field=models.CharField(max_length=20),
        ),
    ]
