# Generated by Django 5.0 on 2024-01-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0005_alter_ad_advertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='one_click_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ad',
            name='thousand_view_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='account_credit',
            field=models.IntegerField(default=0),
        ),
    ]
